const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"寻宠",
                        "menuJump":"列表",
                        "tableName":"chongwu"
                    }
                ],
                "menu":"寻宠"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"寻宠收藏",
                        "menuJump":"列表",
                        "tableName":"chongwuCollection"
                    }
                ],
                "menu":"寻宠收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"寻宠留言",
                        "menuJump":"列表",
                        "tableName":"chongwuLiuyan"
                    }
                ],
                "menu":"寻宠留言"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"动物求助",
                        "menuJump":"列表",
                        "tableName":"dongwu"
                    }
                ],
                "menu":"动物求助"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"求助收藏",
                        "menuJump":"列表",
                        "tableName":"dongwuCollection"
                    }
                ],
                "menu":"求助收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "回复",
                            "删除"
                        ],
                        "menu":"求助留言",
                        "menuJump":"列表",
                        "tableName":"dongwuLiuyan"
                    }
                ],
                "menu":"求助留言"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"领养信息",
                        "menuJump":"列表",
                        "tableName":"dongwuYuyue"
                    }
                ],
                "menu":"领养信息"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告通知",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告通知"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
